CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     name    VARCHAR(255),
                                     surname VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS books (
                                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     title VARCHAR(64) NOT NULL,
                                     author_id BIGINT NOT NULL,
                                     FOREIGN KEY (author_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS outbox(
    id   BIGSERIAL PRIMARY KEY,
    data TEXT NOT NULL
)